sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include: # Required for Python 3.7+
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip install poetry
  - poetry install -vvv
script:
   - poetry run coverage run --source=httprunner-mubu -m unittest discover
   - poetry run coverage report
   - poetry run coveralls
